about/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.about, name='about')
]

blogs/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blogs, name='blogs'),
    path('<int:blog_id>/', views.blog_details, name='blog_details'),
]

my_portfolio_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from main_page import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # main_page
    path('', views.index, name='index'),
    # about
    path('about/', include('about.urls')),
    # blogs
    path('blogs/', include('blogs.urls')),
    # portfolio
    path('projects/', include('portfolio.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    path('', views.projects, name='projects'),
    path('<int:project_id>/', views.project_details, name='project_details'),
]

blogs/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()
    logo = models.ImageField(upload_to='blogs/images', null=True)
    img = models.ImageField(upload_to='blogs/images', null=True)
    date = models.DateField()

    def __str__(self):
        return self.title

main_page/models.py
from django.db import models


class Menu(models.Model):
    title = models.CharField(max_length=50)
    url = models.CharField(max_length=50)

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField(max_length=500)
    source = models.FileField(upload_to='portfolio/uploads/source')
    image = models.ImageField(upload_to='portfolio/uploads', null=True)

    def __str__(self):
        return self.title

about/views.py
from django.shortcuts import render
from main_page.models import Menu


def about(request):
    menu = Menu.objects.all()
    return render(request, 'about/about.html', {'menu': menu})

blogs/views.py
from django.shortcuts import render, get_object_or_404
from main_page.models import Menu
from .models import Blog


def blogs(request):
    menu = Menu.objects.all()
    blogi = Blog.objects.all().order_by('-date')
    return render(request, 'blogs/blogs.html', {'menu': menu, 'blogs': blogi})


def blog_details(request, blog_id):
    menu = Menu.objects.all()
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blogs/blog_details.html', {'menu': menu, 'blog': blog})

main_page/views.py
from django.shortcuts import render
from .models import Menu


def index(request):
    menu = Menu.objects.all()
    return render(request, 'main_page/index.html', {'menu': menu})

portfolio/views.py
from django.shortcuts import render, get_object_or_404
from django.http import FileResponse
from main_page.models import Menu
from .models import Project


def projects(request):
    menu = Menu.objects.all()
    my_projects = Project.objects.all()
    return render(request, 'portfolio/portfolio.html', {'menu': menu, 'projects': my_projects})


def project_details(request, project_id):
    menu = Menu.objects.all()
    project = get_object_or_404(Project, pk=project_id)
    return render(request, 'portfolio/project_details.html', {'menu': menu, 'project': project})

templates/about/about.html
{% extends 'main_page/base.html' %}
{% load static %}

{% block css %} <link rel="stylesheet" href="{% static 'css/about.css' %}"> {% endblock %}

{% block content %}
    <section>
        <h1 >Информация о разработчике</h1>

        <div class="info-block container">
            <div class="dev-block">
                <div class="auth-img">
                    <img src="{% static 'about/auth-img.jpg' %}" width="400" height="300" alt="фотография">
                </div>
                <div class="auth-info">
                    <p>Автор: Лукьянов Павел Юрьевич</p>
                    <p>Группа: Python216</p>
                    <p>Направление: Web Python Development</p>

                    <h3>Изучаемые языки:</h3>
                    <ul>
                        <li>SQL</li>
                        <li>Python</li>
                        <li>HTML, CSS</li>
                    </ul>
                </div>
                <div class="other-links">
                    <h3>Прочие ссылки: </h3>
                    <a href="https://github.com/pavellukyanov08?tab=repositories"><p>GitHub-профиль разработчика</p></a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/blogs/blog_details.html
{% extends 'main_page/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/details.css' %}">
{% endblock %}

{% block content %}
    <div class="details container">
        <h2>{{ blog.title }}</h2>
        <p>Дата публикации: {{ blog.date | date:'d.m.Y' }}</p>
        <img src="{{ blog.img.url }}" alt="Изображение">
        <div class="details-text">
            <p>{{ blog.description | safe }}</p>
        </div>
    </div>
{% endblock %}

templates/blogs/blogs.html
{% extends 'main_page/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/blogs.css' %}">
{% endblock %}

{% block content %}
    <h1>Статьи</h1>
    <p class="count container">Постов: {{ blogs.count }}</p>

    {% for blog in blogs %}
        <div class="elements container">
            <div class="top">
                <a href="{% url 'blog:blog_details' blog.id %}">{{ blog.title }}</a>
                <img src="{{ blog.logo.url }}" width="50" height="50" alt="Логотип">
            </div>


            <div class="blog-text">
                <p>{{ blog.description | striptags | truncatechars:360 }}</p>
            </div>
            <p> {{ blog.date | date:'d.m.Y' }}</p>
        </div>
    {% endfor %}

{% endblock %}

templates/main_page/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block css %} {% endblock %}
    <title>{{ title }}</title>
</head>
<body>
    <header class="page-header">
        <div class="page-header__wrapper container">
            <div class="page-header__logo">
                <a href="{% url "index" %}">
                    <img src="{% static 'main_page/my_logo.svg' %}" width="80" height="80" alt="Логотип автора">
                </a>
            </div>

            <nav class="site-nav page-header__site-nav">
                {% for el in menu %}
                <ul class="site-nav__list">
                    <li class="site-nav__item"><a href="{{ el.url }}">{{ el.title }}</a></li>
                </ul>
                {% endfor %}
            </nav>
        </div>
    </header>

    {% block content %}

    {% endblock %}
</body>
</html>

templates/main_page/index.html
{% extends 'main_page/base.html' %}
{% load static %}

{% block css %} <link rel="stylesheet" href="{% static 'css/style.css' %}"> {% endblock %}

{% block content %}
    <section class="page-upper">
        <div class="sale container">
            <div class="last-chance">
                <h2>Последний шанс</h2>
            </div>

            <div class="last-chance__button">
                <a href="#">Стулья</a>
                <a href="#">Диваны</a>
                <a href="#">Кресла</a>
            </div>

            <div class="product-sale__info">
                <div class="product-sale__item">
                    <div class="product-sale__above"></div>

                    <div class="product-sale__name">
                        <h3>Стул "Карамель"</h3>
                    </div>

                    <div class="product-sale__price">
                        <p class="product-price__new">$195</p>
                        <p class="product-price__old">$245</p>
                    </div>

                    <div class="product-sale__img">
                        <img src="{% static 'main_page/chair-caramel-desktop.png' %}" alt="стул">
                    </div>

                    <div class="product-sale__buy">
                        Купить
                    </div>
                </div>

                <div class="product-sale__item">
                    <div class="product-sale__above"></div>

                    <div class="product-sale__name">
                        <h3>Стул "Облако"</h3>
                    </div>

                    <div class="product-sale__price">
                        <p class="product-price__new">$200</p>
                        <p class="product-price__old">$250</p>
                    </div>

                    <div class="product-sale__img">
                        <img src="{% static 'main_page/chair-cloud-desktop.jpg' %}" alt="стул">
                    </div>

                    <div class="product-sale__buy">
                        Купить
                    </div>
                </div>

                <div class="product-sale__item">
                    <div class="product-sale__above"></div>

                    <div class="product-sale__name">
                        <h3>Стул "Сова"</h3>
                    </div>

                    <div class="product-sale__price">
                        <p class="product-price__new">$240</p>
                        <p class="product-price__old">$260</p>
                    </div>

                    <div class="product-sale__img">
                        <img src="{% static 'main_page/chair-owl-desktop.png' %}" alt="стул">
                    </div>

                    <div class="product-sale__buy">
                        Купить
                    </div>
                </div>

                <div class="product-sale__item">
                    <div class="product-sale__above"></div>

                    <div class="product-sale__name">
                        <h3>Стул "Мая"</h3>
                    </div>

                    <div class="product-sale__price">
                        <p class="product-price__new">$280</p>
                        <p class="product-price__old">$330</p>
                    </div>

                    <div class="product-sale__img">
                        <img src="{% static 'main_page/chair-maya-desktop.jpg' %}" alt="стул">
                    </div>

                    <div class="product-sale__buy">
                        Купить
                    </div>
                </div>

                <div class="product-sale__item">
                    <div class="product-sale__above"></div>
                    <div class="product-sale__name">
                        <h3>Стул "Месси"</h3>
                    </div>

                    <div class="product-sale__price">
                        <p class="product-price__new">$280</p>
                        <p class="product-price__old">$305</p>
                    </div>

                    <div class="product-sale__img">
                        <img src="{% static 'main_page/chair-messi-desktop.png' %}" alt="стул">
                    </div>

                    <div class="product-sale__buy">
                        Купить
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="page-middle">
        <div class="back-img container">
            <img src="{% static 'main_page/back-img.jpg' %}" alt="задний фон">
        </div>
    </section>

    <footer class="footer">
        <div class="basement container">
            <div class="top-line">
                <div class="top-line__logo">
                    <img src="{% static 'main_page/logo.svg' %}" alt="logo">
                </div>

                <div class="top-line__menu">
                    <a class="top-line__menu-item" href="#">Доставка</a>
                    <a class="top-line__menu-item" href="#">Оплата</a>
                    <a class="top-line__menu-item" href="#">Контакты</a>
                    <a class="top-line__menu-item" href="#">Гарантии</a>
                </div>
            </div>

            <div class="bottom-line">
                <div class="phone-number">
                    <img src="{% static 'main_page/icon-phone.svg' %}" alt="phone-icon">
                    <p>+7(495) 205-28-14</p>
                </div>

                <div class="main-adress">
                    <img src="{% static 'main_page/icon-mail.svg' %}" alt="icon-main">
                    <p>callium@gmail.com</p>
                </div>
            </div>

            <div class="rights">
                <img src="{% static 'main_page/line-botton.svg' %}" alt="line">
                <p>© 2018 «Callium» — Сайт по продаже дизайнерской мебели. Все права защищены.</p>
            </div>
        </div>
    </footer>
{% endblock %}

templates/portfolio/portfolio.html
{% extends 'main_page/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/portfolio.css' %}">
{% endblock %}

{% block content %}
    <h1>Мои проекты</h1>
    <p class="count container">Количество проектов: {{ projects.count }} (проекты будут дополняться)</p>

    {% for project in projects %}
        <div class="projects container">
            <div class="top">
                <a href="{% url 'project:project_details' project.id %}">{{ project.title }}</a>
            </div>


            <div class="description-text">
                <p>{{ project.description | striptags | truncatechars:360 }}</p>
            </div>
            <p> {{ project.date | date:'d.m.Y' }}</p>
        </div>
    {% endfor %}

{% endblock %}

templates/portfolio/project_details.html
{% extends 'main_page/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/project_details.css' %}">
{% endblock %}

{% block content %}
    <div class="details container">
        <h2>{{ project.title }}</h2>
        <div class="details-text">
            <p>{{ project.description | safe }}</p>
        </div>

        <div class="project-img">
            <img src="{{ project.image.url }}" alt="Изображение проекта">
        </div>
        <div class="source-project">
            <p>Скачать исходный код проекта или посмотреть его на GitHub вы можете ниже:</p>
            <div class="download-project">
                <a class="button" href="{{ project.source.url }}" download>Скачать файл</a>
                <h3>/</h3>
                <a class="link" href="https://github.com/pavellukyanov08/Furniture-design">Репозиторий проекта</a>
            </div>
        </div>
    </div>
{% endblock %}